#!/usr/bin/env bash
# guard-layer: source --no-heartbeat
# check-handover-staleness.sh (T-2883, G-019 prevention for the T-2882 class)
#
# THE DEFECT THIS GUARDS
#
# `.context/handovers/LATEST.md` is the first artefact read at every session start
# (CLAUDE.md §Session Start Protocol) and at every post-compaction recovery. T-2882
# found that its "Suggested First Action" — the single line the protocol tells every
# session to act on — had been the byte-identical string `Continue T-1457` for 68
# consecutive handovers, and `Continue T-1166` for the 916 before that, because the
# generator ranked candidates by task id compared as a STRING and printed the first
# agent-owned one. That is a constant until the task closes. The session's real focus
# ranked 17th of 123 and was never named.
#
# The fix was one thing; the blindness was another. NOTHING IN THE FRAMEWORK COMPARED
# ONE HANDOVER TO THE NEXT, so a value repeating 916 times produced no signal at all.
# Every existing check reads a single artefact in isolation and is therefore
# structurally incapable of seeing a constant as a constant. That is the gap this
# closes, and it is why axis A is a cross-file comparison rather than a lint.
#
# THE THREE AXES, AND WHY ONLY TWO OF THEM FIRE
#
#   Axis A — CONSTANT SUGGESTED ACTION (fires). The Suggested First Action line is
#     byte-identical across the last N handovers. This is the axis that actually found
#     T-2882, and it is self-clearing: the moment the value moves, it goes green.
#
#   Axis B — FABRICATED LITERAL REGRESSION (fires). LATEST.md carries a bare `None` or
#     `See gaps register above.` as a narrative section body — the literals T-2882
#     removed. A regression guard, green on the fixed tree.
#
#   Axis C — UNENRICHED HANDOVERS (counted and reported, NEVER fired on). Every
#     handover is generated by the T-136 auto-handover with no agent in the loop, so
#     `enrichment_status: pending` is the NORMAL state today. Firing on it would make
#     this check permanently red, which is precisely how a guard teaches its operator
#     to stop reading it — the fatigue failure T-2833 documented when its own first
#     draft produced 58 legitimate findings. The count is printed on BOTH output paths
#     so a green is never ambiguous between "enrichment happened" and "the filter ate
#     it". Promoting C to a firing axis is a deliberate decision for whenever
#     enrichment is actually wired, not something to slip in here.
#
# SCOPE — read a green narrowly (T-2680)
#
# This detects a CONSTANT suggested action and a KNOWN set of fabricated literals. It
# does NOT verify that a handover is accurate, useful, or genuinely enriched. A
# handover whose sections are all filled with confident nonsense passes cleanly. Both
# output paths say so.
#
# Exit: 0 = nothing firing · 1 = axis A or B firing · 2 = tooling error.
# Fail-closed: a missing directory, an unreadable allowlist, absent python3, or a
# corpus of zero handovers all exit 2 — never a vacuous clean.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HANDOVERS_DIR="${HANDOVER_STALENESS_DIR:-$REPO_ROOT/.context/handovers}"
ALLOWLIST=""
WINDOW="${HANDOVER_STALENESS_WINDOW:-10}"
JSON=0
QUIET=0

SCOPE_NOTE="Scope: detects a CONSTANT Suggested First Action and known fabricated literals. It does NOT verify that a handover is accurate, useful, or genuinely enriched."

die() { printf 'check-handover-staleness: %s\n' "$1" >&2; exit 2; }

while [ $# -gt 0 ]; do
    case "$1" in
        --json)           JSON=1; shift ;;
        --quiet)          QUIET=1; shift ;;
        --no-heartbeat)   shift ;;   # accepted for guard-layer parity; this check writes none
        --window)         WINDOW="${2:-}"; shift 2 ;;
        --handovers-dir)  HANDOVERS_DIR="${2:-}"; shift 2 ;;
        --allowlist)      ALLOWLIST="${2:-}"; shift 2 ;;
        -h|--help)
            sed -n '2,50p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
            exit 0 ;;
        *) die "unknown argument: $1" ;;
    esac
done

case "$WINDOW" in
    ''|*[!0-9]*) die "--window must be a positive integer (got: '$WINDOW')" ;;
esac
[ "$WINDOW" -ge 2 ] || die "--window must be at least 2 — a single handover cannot be compared to anything"

command -v python3 >/dev/null 2>&1 || die "python3 not found (fail-closed: cannot report clean without looking)"
[ -d "$HANDOVERS_DIR" ] || die "handovers directory not found: $HANDOVERS_DIR"

# Allowlist resolution: explicit flag wins, else the git-tracked home (T-2681).
if [ -z "$ALLOWLIST" ]; then
    ALLOWLIST="$REPO_ROOT/.context/checks/handover-staleness-allowlist"
fi
if [ -e "$ALLOWLIST" ] && [ ! -r "$ALLOWLIST" ]; then
    die "allowlist exists but is not readable: $ALLOWLIST (fail-closed)"
fi

export HS_DIR="$HANDOVERS_DIR" HS_WINDOW="$WINDOW" HS_ALLOWLIST="$ALLOWLIST" \
       HS_JSON="$JSON" HS_QUIET="$QUIET" HS_SCOPE="$SCOPE_NOTE"

python3 <<'PYEOF'
import glob, json, os, re, sys

d        = os.environ['HS_DIR']
window   = int(os.environ['HS_WINDOW'])
allowp   = os.environ['HS_ALLOWLIST']
as_json  = os.environ['HS_JSON'] == '1'
quiet    = os.environ['HS_QUIET'] == '1'
scope    = os.environ['HS_SCOPE']

def tooling(msg):
    print(f'check-handover-staleness: {msg}', file=sys.stderr)
    sys.exit(2)

# Session handovers are named S-<date>-<time>.md; LATEST.md is a symlink to one of
# them. Sorting by name is chronological because the stamp is zero-padded.
files = sorted(p for p in glob.glob(os.path.join(d, 'S-*.md')) if os.path.isfile(p))
if not files:
    # Fail-closed: an empty corpus is "could not look", never "looked and found nothing".
    tooling(f'no handovers found under {d} (fail-closed: an empty corpus is not a clean result)')

allow = set()
if os.path.exists(allowp):
    try:
        with open(allowp) as fh:
            for line in fh:
                line = line.split('#', 1)[0].strip()
                if line:
                    allow.add(line)
    except OSError as e:
        tooling(f'allowlist unreadable: {e}')

SUGGEST_RE = re.compile(r'^## Suggested First Action\s*$', re.M)

def suggested_action(path):
    """First non-blank, non-heading line of the Suggested First Action section."""
    try:
        with open(path, encoding='utf-8', errors='replace') as fh:
            text = fh.read()
    except OSError:
        return None
    m = SUGGEST_RE.search(text)
    if not m:
        return None
    for line in text[m.end():].splitlines():
        s = line.strip()
        if not s:
            continue
        if s.startswith('## '):
            break
        if s.startswith('_') or s.startswith('<!--'):
            continue   # the T-2882 mechanical-fallback label, not the value itself
        return s
    return None

recent = files[-window:]
actions = [(os.path.basename(p), suggested_action(p)) for p in recent]
present = [(f, a) for f, a in actions if a]

firing = []

# ── Axis A — constant Suggested First Action across the window ──────────────────
distinct = {a for _, a in present}
if len(present) >= window and len(distinct) == 1:
    val = next(iter(distinct))
    if val not in allow:
        firing.append({
            'axis': 'A',
            'kind': 'constant-suggested-action',
            'value': val,
            'window': len(present),
            'detail': (f'Suggested First Action has been byte-identical across the last '
                       f'{len(present)} handovers. A value that never moves is not a '
                       f'recommendation; it is a constant presented as one (T-2882).'),
        })

# ── Axis B — fabricated narrative literals in the newest handover ───────────────
FABRICATED = ('None', 'See gaps register above.')
NARRATIVE = ('Decisions Made This Session', 'Things Tried That Failed',
             'Open Questions / Blockers', 'Gotchas / Warnings for Next Session')
newest = recent[-1]
try:
    with open(newest, encoding='utf-8', errors='replace') as fh:
        newest_text = fh.read()
except OSError as e:
    tooling(f'cannot read newest handover {newest}: {e}')

for section in NARRATIVE:
    m = re.search(r'^## ' + re.escape(section) + r'\s*$', newest_text, re.M)
    if not m:
        continue
    body = []
    for line in newest_text[m.end():].splitlines():
        if line.strip().startswith('## '):
            break
        if line.strip():
            body.append(line.strip())
    if body and body[0] in FABRICATED:
        sig = f'{section}::{body[0]}'
        if sig not in allow:
            firing.append({
                'axis': 'B',
                'kind': 'fabricated-literal',
                'value': sig,
                'file': os.path.basename(newest),
                'detail': (f'"{section}" reads "{body[0]}" — a generator-supplied literal '
                           f'indistinguishable from a finding. T-2882 replaced these with '
                           f'explicit [TODO] markers; this is a regression.'),
            })

# ── Axis C — unenriched count (counted and reported, NEVER firing) ──────────────
unenriched = 0
for p in recent:
    try:
        with open(p, encoding='utf-8', errors='replace') as fh:
            head = fh.read(4096)
    except OSError:
        continue
    if re.search(r'^enrichment_status:\s*pending\s*$', head, re.M):
        unenriched += 1

result = {
    'ok': not firing,
    'firing': firing,
    'firing_count': len(firing),
    'window': len(recent),
    'handovers_total': len(files),
    'unenriched_in_window': unenriched,
    'acknowledged_count': len(allow),
    'axes': {'A': 'constant-suggested-action (fires)',
             'B': 'fabricated-literal (fires)',
             'C': 'unenriched (counted, never fires)'},
    'scope': scope,
}

if as_json:
    print(json.dumps(result, indent=2))
    sys.exit(1 if firing else 0)

if firing:
    print(f'check-handover-staleness: {len(firing)} finding(s) across {len(recent)} handover(s)')
    print()
    for f in firing:
        print(f"  [axis {f['axis']}] {f['kind']}: {f['value']}")
        print(f"      {f['detail']}")
        print()
    print(f'  ({unenriched}/{len(recent)} in window are enrichment_status: pending — '
          f'counted, not a finding: see axis C in the header of this script)')
    print(f'  {scope}')
    sys.exit(1)

if not quiet:
    print(f'check-handover-staleness: clean ({len(recent)} handover(s) in window, '
          f'{len(distinct)} distinct suggested action(s), {len(allow)} acknowledged)')
    print(f'  ({unenriched}/{len(recent)} in window are enrichment_status: pending — '
          f'counted, not a finding)')
    print(f'  {scope}')
sys.exit(0)
PYEOF
